query Articles($slug: String!)  {  
  articles(where: {
    	slug: $slug
  	}) {
    id
    slug
    title
    published
    summary
    date
    categories { name }
    body
    image { formats }
    author {
      name
      title
      company
      avatar { formats }
    }
  }
}