query Articles {
  articles(sort: "id:desc", where: { published: true }) {
    id
    slug
    title
    published
    summary
    date
    categories {
      name
    }
    image {
      formats
    }
    author {
      name
      title
      company
      avatar {
        formats
      }
    }
  }
}
